import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#b8f2eb",
    justifyContent: "center",
    padding: 30,
  },
  title: {
    fontSize: 42,
    fontWeight: "900",
    textAlign: "center",
    color: "#f707c7",
    textShadowColor: "#b8f2eb",
    textShadowRadius: 10,
    marginBottom: 40,
  },
  label: {
    color: "#b8f2eb",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 6,
  },
  input: {
    borderWidth: 2,
    borderColor: "#2ae880",
    backgroundColor: "#e82ab5",
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 20,
    padding: 12,
    marginBottom: 25,
    borderRadius: 12,
    // placeholder will be weird handled in component via Animated
  },
  button: {
    backgroundColor: "#00FF00",
    padding: 20,
    borderRadius: 30,
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#FF00FF",
    shadowColor: "#FF00FF",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 20,
  },
  buttonText: {
    fontSize: 28,
    fontWeight: "900",
    color: "#e82ab5",
    textShadowColor: "#e82ab5",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 8,
  },
  toggleContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 35,
  },
  toggleText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FF33CC",
    textDecorationLine: "underline",
  },
  error: {
    marginTop: 15,
    color: "#FF0033",
    fontWeight: "900",
    fontSize: 18,
    textAlign: "center",
    textShadowColor: "#AA0000",
    textShadowRadius: 8,
  },
});
